name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - releases/**
  push:
    branches:
      - main
      - releases/**
      - fix/**
      - v4*

jobs:
  # End to end save and restore
  test-save:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part_size: [32]
        queue_size: [4, 8]
      fail-fast: false
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Generate files in working directory
      shell: bash
      run: |
        __tests__/create-cache-files.sh ${{ runner.os }} test-cache
        dd if=/dev/urandom of=test-cache/random-1gb.bin bs=1M count=1024
    - name: Generate files outside working directory
      shell: bash
      run: __tests__/create-cache-files.sh ${{ runner.os }} ~/test-cache
    - name: Save cache
      uses: ./
      env:
        UPLOAD_PART_SIZE: ${{ matrix.part_size }}
        UPLOAD_QUEUE_SIZE: ${{ matrix.queue_size }}
      with:
        key: test-${{ runner.os }}-${{ github.run_id }}-${{ matrix.part_size }}-${{ matrix.queue_size }}
        path: |
          test-cache
          ~/test-cache
  test-restore:
    needs: test-save
    strategy:
      matrix:
        part_size: [8, 16]
        queue_size: [8, 12]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Restore cache
      uses: ./
      env:
        DOWNLOAD_PART_SIZE: ${{ matrix.part_size }}
        DOWNLOAD_QUEUE_SIZE: ${{ matrix.queue_size }}
      with:
        key: test-${{ runner.os }}-${{ github.run_id }}-${{ matrix.part_size }}-${{ matrix.queue_size }}
        restore-keys: |
          test-${{ runner.os }}-${{ github.run_id }}-${{ matrix.part_size }}-
          test-${{ runner.os }}-${{ github.run_id }}-
        path: |
          test-cache
          ~/test-cache
    - name: Verify cache files in working directory
      shell: bash
      run: __tests__/verify-cache-files.sh ${{ runner.os }} test-cache
    - name: Verify cache files outside working directory
      shell: bash
      run: __tests__/verify-cache-files.sh ${{ runner.os }} ~/test-cache

  test-container:
    runs-on: runs-on,runner=2cpu-linux-arm64
    container:
      image: ubuntu:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Test in container
      run: |
        __tests__/create-cache-files.sh Linux test-cache
        __tests__/verify-cache-files.sh Linux test-cache
    - name: Save cache
      uses: ./
      with:
        key: test-container-${{ github.run_id }}
        path: test-cache
